const os=require('os')
console.log(os.arch())
console.log(os.hostname())
console.log(os.platform())
console.log(os.tmpdir())
console.log(os.type())

const path=require('path')
console.log(path.parse('C:/Users/ANSHU YADAV/Documents/Sem IV'))
const mypath=path.parse('C:/Users/ANSHU YADAV/Documents/Sem IV')
console.log(mypath.dir)